### ISSUE TITLE
Unable to load webcontentresolver.py module

### ISSUE THREAD

**Issue by pentagramz** [mwrlabs/drozer-modules#7]
I am Unable to load webcontentresolver.py module

Kindly help
![drozer1](https://cloud.githubusercontent.com/assets/7072014/15678464/0ddbbf54-276c-11e6-85d3-7cbff07436d0.JPG)

**Comment by amarekano** [comment]
Hi @pentagramz, this should be fixed in version 2.4.3. Please find the latest drozer release at https://github.com/mwrlabs/drozer/releases
